# Generated by Django 5.2.8 on 2025-11-13 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufactuter',
            new_name='Manufacturer',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='manufactuter',
            new_name='manufacturer',
        ),
    ]
