# Generated by Django 5.2.8 on 2025-11-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0002_rename_manufactuter_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
